### ISSUE TITLE
What to do when entire packet was not parsed.

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#129]
*EDIT* : I think the proper way to deal with this is emitting an error whenever a packet isn't properly parsed. We may then catch it, and kick the associated client in case of a server.

Currently, I have a debug message I forgot to remove that is triggered when the entirety of a packet wasn't parsed. This is meant to catch errors in the deserializer. https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L1576 . This obviously needs to be replaced by a call to ``debug``, probably with more information about the packet. 

The question is, what should we do in this case ? Emit an 'error' event in the client ? This could potentially crash the server if not caught.

**Comment by adam-janis** [comment]
Having this issue as well... trying to connect client with circa 20+ online players, but I am not able to listening for chat events. 
Is any chance to limit parsing just for few listeners? I dont need entity updates.

Or.. is there any chance to try to set higher limits for packets size? 
Any suggest what I should do to get it working? :) 
![image](https://cloud.githubusercontent.com/assets/3592620/6783421/83a03d2a-d171-11e4-9b79-3e91999d7356.png)

Many thanks,
Adam

**Comment by roblabla** [comment]
Receiving this message means the protocol parser is broken. Which client are you using ?

**Comment by adam-janis** [comment]
I am using protocol version 0.13.1 and connecting to server v1.8.. which should be supported, isn't?

**Comment by roblabla** [comment]
1.8.1 is the server version you should be using. Also, i just released 0.13.2, which fixes a little bug in the world particle packet, but that shouldn't be an issue. 

Could you do `export NODE_DEBUG='mc-proto'`, run the server, and paste the output in a gist/pastebin ? That will give me the data I need to debug the problem.

**Comment by adam-janis** [comment]
@roblabla, here it is.. hopefully this will help! 
http://pastebin.com/yUAuTEBE
http://pastebin.com/NsgiE4Ah
Thank you very much

**Comment by roblabla** [comment]
There's no "DID NOT PARSE THE WHOLE THING" message in there... Urg.

**Comment by adam-janis** [comment]
Yeah... not helpful then... protocol still isn't catching events (I am basically trying just to catch chat event, without chance..)

**Comment by roblabla** [comment]
@adam-janis do you know what software the server is running ?

**Comment by adam-janis** [comment]
It is bungeecord... I already wrote to owner to give me more details, I
will let you know as soon as I'll have them

**Comment by adam-janis** [comment]
Yes, it was told me that its running on bungeecord with 1.7.2 - 1.8.x protocol..

**Comment by roblabla** [comment]
ah, that may be the problem if it attempts to do a "too" clever protocol hack. I'll investigate.

**Comment by adam-janis** [comment]
Will you need any more info, dumps , etc. to investigate?

**Comment by roblabla** [comment]
Not much. This issue should be split in two though.

1. What to do when we failed to parse
2. Figure out why bungeecord makes us fail to parse. I'll open a new issue for this one.

**Comment by rom1504** [comment]
Discussion in #208 is kind of related to this.

**Comment by roblabla** [comment]
This should really emit an error, along with the buffer it failed to read.

**Comment by roblabla** [comment]
We're throwing an error now when the packet wasn't parsed in its entirety. I'm closing this.
